- hosts: ansislave
  tasks: 
  - name: Update and upgrade apt packages
    become: true
    apt:
      update_cache: yes

  - name: Install apache httpd  (state=present is optional)
    become: true
    apt:
      name: apache2
      state: present

  - name: reload service httpd, in all cases
    systemd:
      name: apache2
      state: stopped
  - name: reload service httpd, in all cases
    systemd:
      name: apache2
      state: started

- hosts: ansimaster
  tasks:
  - name: Install the package "Lynx"
    become: true
    apt:
      name: lynx

